### ISSUE TITLE
繰り返しと条件分岐

### ISSUE THREAD

**Issue by cehl-kurage** [shinonome-inc/PythonTutorialForDSCourse#3]
# 追加したい内容について
`for`, `while` `if` を使って実装してもらい、それらの使い方になじんでもらう

# タスクの詳細

- [ ] 課題の模範解答を作成した

**Comment by cehl-kurage** [comment]
@yuji96 
`match` ~ `case` 文はやらんときますか？

**Comment by cehl-kurage** [comment]
## while 文を利用するコード
### テーマ: ユークリッドの互除法
https://manabitimes.jp/math/672
```
# aとbの最大公約数を求めよ
a, b = map(int, input().split())
while r != 0:
r = a % b
a = b
b = r
```

**Comment by cehl-kurage** [comment]
## for 文を利用するコード
### テーマ: 台形積分
（関数を使うのと、関数を使わないのどっちがややこしいだろう？）
https://manabitimes.jp/math/1088
```python
f = lambda x: # xの多項式
min_x, max_x = map(float, input().split()) # 定義域の与え方どうしよう
width = float(input()) # 分割の幅
num_divide = (max_x - min_x) // width # 分割数
for i in range(num_divide):
    ...
```

**Comment by yuji96** [comment]
match はいっかな。台形積分ってforにならない？

**Comment by cehl-kurage** [comment]
@yuji96 
forでもいいんですけど、使いたい機能を網羅しようとしたらこうなりました 
レビューの際は`for`で書いててもOKとしてもいいかなとは思ったんですけど、歪ですかね

**Comment by yuji96** [comment]
for で書けるものは for で書くべきなので避けたい．正直，while の使い所はあまりないからユークリッドだけでも良いかもしれない．ちなみに，python を書くことよりもプログラムを思いつかせたいから，問題出す際は「for 文を使って...」みたいな導入は無くても良いかも．（ググったら出てきちゃうけど）

**Comment by cehl-kurage** [comment]
承知です

**Comment by yuji96** [comment]
while では書けるけど for では書けない例として、マシンイプシロンも良いかも。

```python
a = 1
while a + 1 != 1:
    a /= 2
print(a * 2)
```

（解の公式の結果で 10 の -17 乗が出てきちゃうから、これ課題に追加したい。）

**Comment by cehl-kurage** [comment]
なるほど。
じゃあマシンイプシロンの課題も追加します  
複数あっても仕方ないかとは思うんですが、置き換えますか？

**Comment by yuji96** [comment]
多分、ちゃんと読んで理解していれば一瞬で解けちゃうので複数あったほうが良いと思います。

**Comment by cehl-kurage** [comment]
了解しました
それぞれ追加したのでPRのレビューお願いします

**Comment by yuji96** [comment]
レビューの仕方が分からず滞っちゃてたけど、PR で挙げられていたこの 4 つで問題数は丁度いいと思います。

- for
  - 素数判定
  - （台形積分？）
    - 関数を知らない状態で実装すると、コードがきれいにならなそうという懸念がある。
    - `math.sin` とかを使うならありかも。曲線なのに積分値が整数になってきれいだし。
- while
  - ユークリッドの互除法
  - マシンイプシロン
    - 問題文書くときに背景を書きたい。（yuji 担当?）

一応、教材側に `input` 関数の説明は欲しいですね。

**Comment by cehl-kurage** [comment]
了解です
問題文の作成は明日になるかもしれません...
