### ISSUE TITLE
pandas課題を修正

### ISSUE THREAD

**Issue by cehl-kurage** [shinonome-inc/PythonTutorialForDSCourse#8]
# 修正内容
pandas課題を修正する  
読み物はChainerTutorialのものを使うこととするので、そこにない内容はいったん除く  
scikit learnを使うのに苦労しないのが目標

# 修正の理由

# タスク
- [ ] 学習すべき機能をリストアップ
- [ ] 課題を作成した

**Comment by cehl-kurage** [comment]
### 学習する必要がある機能
- 欠損値の処理
- to_csv(), read_csv()
- データの選択（文字列の列をdrop?）
- one-hot encoding
- label encoding
- 正規化

最後に必要な前処理をすべて実装した関数を書かせるとか？

**Comment by cehl-kurage** [comment]
@yuji96 pandas課題のコンテンツ案、こんな感じでどうでしょう

**Comment by yuji96** [comment]
> 読み物はChainerTutorialのものを使うこととするので、そこにない内容はいったん除く

chainer tutorial にある部分だけだと、今後の最終課題や案件などでつまずく可能性がかなり高いと思う。

---

これは pandas 関係ない気がする。

> one-hot encoding
> label encoding
> 正規化

---

- データの選択（文字列の列をdrop?）
- 条件によるデータの選択

↑ここで挙げられている「データ選択」は、時系列データなら `datetimeindex` を使って日時に基づいて選択したり、ちょっと汚いデータだと `df.str.contains` を使って文字列に基づいて選択したりなど、いろんなケースがある。

現状で pandas 課題をみんな乗り越えているなら、同じクリアの問題量・難易度で良いかもしれない。

**Comment by cehl-kurage** [comment]
なるほど。
逆に現在のpandas課題で不足と感じている点があれば聞いておきたいです

**Comment by yuji96** [comment]
現在の pandas 課題がちゃんと解ければ十分だと思います。若干むずいのかもしれないですが、現状問題なければ今のままでいいと思います。

ただ、chainer tutorial が pandas 課題を始めとした日常的(?)な pandas 操作をカバーできているのか懸念があります。（課題というより chainer tutorial が不足しているように感じる。）

ただ、どうせ学んでいなかったことに直面することになるので、課題を検索力を伸ばすためのものとして修正しないのもありだと思います。下のように、分からなかったらヒントを表示できるようにすれば、問題はそのままでもスムーズに解けるように成るかもしれません。（すぐ見ちゃったら検索力伸びないけど。第一ヒントは、検索キーワードだけのほうが良いかな。）

<details>
<summary>ヒント</summary>
文字列検索: 
<a href="https://note.nkmk.me/python-pandas-str-contains-match/">https://note.nkmk.me/python-pandas-str-contains-match/</a>
</details>

**Comment by cehl-kurage** [comment]
いずれすべて調べながらやることになるという意識は根付かせたい気がしますね
キーワードを表示するくらいがいいかなと思います
じゃあ、そういう方向でなにか誘導できたりしないか見直してみます。

**Comment by yuji96** [comment]
ありがとうございます 🙇
